githubteacher/developers-november-2016

a
dj-file.md

This work will close #14 
##Things left

Dj sandiego

---

vish-atl.md

This is an extended message. Here you can provide detailed information.
This work will close #15

Created a blank file for vish ATL.

---

sree.cmd

this will fix #28 
things left

created a blank file

---

al8b8-Guadalajara.md

Create a file for al8b8-Guadalajara

---

githubteacher-raleigh.md

Create a file for githubteacher raleigh

---

ankitsehgal101-hometown.md

Added new file in the process of learning github
this will close #65 
you're chillin

This is my first commit

---

vish-atl.md

Added places to eat

---

tysonshaw-apex.md

Created a file for tysonshaw apex

---

anandseeman-philadelphia.md

I created a file that will close #24

Create a couple of files to anandseeman-philadelphia

---

mhalano-brazil2.md

I needed to do all over again.

I messed up

---

jo-chi.md

this work will close #19 
-[] place to eat
-[] things to do

File for jo-chi

---

chartek-chicago.md

Create a file for chartek chicago

---

ehertlein-lasvegas.md

created a blank file for ehertlein las vegas

---

stippur87-mission.md

Create a file for stippur87 mission

---

newstuff.md

Another File.

---

panguluru-atlanta.md

This work will close #33 
- [] Add a list of places
- [] Fun things

Create a file for panguluru branch

---

aschulman-chicago.md

This is my extended message.
This work will close #31

Created a file for aschulman chicago

---

AmishP.md

Created a file for AmishP

---

emcowen40-Chicago.md

This is my extended commit message. This will close #21 
There's more stuff to do.

This is my summary commit message for my new file commit

---

dreynolds.md

i made this change because i felt like it, close #17

Created a file for dreynolds

---

RobertWalton-Chicago.md

Created a blank file RobertWalton-Chicago.md for class

---

sprathipati-firstone.md

First file on git Repository

---

jasmine-liu.md

This will close #47 
Here is what left to do:
-[] A list of places to eat
-[] A list of places to visit

First commit

---

michelleegg-seattle.md

This is my extended commit message, which indicates my severe level of
commitment. After two carriage returns, I could go on forever.
Editted for pull request indication. This work will close #45

Created a blank file for michelleegg seattle

---

jeffreykey-chicago.md

Created a file for jeffreykey chicago

---

sdykstra-nashville.md

Created a blank file for sdykstra-nashville

---

ClassDemoFile

adding places to surf

---

hex7cd-dachau.md

Created a blank file for hex7cd dachau

---

whatwouldhoneybadgerdo-raleigh.md

Created a file for Raleigh, NC.

---

ryanschaeffer-denver.md

This work will open #36 
[ ] task for me

Create a file for ryanschaeffer-hometown
